---
- name: Configuring switches
  hosts: switches
  gather_facts: false

  tasks:
    - name: Set Logging synchronous for line vty
      ios_config:
        lines:
          - logging synchronous
        parents: line vty 0 4
      tags: console

    - name: Configure switch VLANs
      cisco.ios.ios_vlans:
        config:
          - name: "{{ item.name }}"
            vlan_id: "{{ item.id }}"
            state: active
            shutdown: disabled
      loop: "{{ vlans }}"

    - name: Turn on interfaces
      ios_interfaces:
        config:
          - name: "{{ item.name }}"
            description: "{{ item.description }}"
            enabled: false
        state: merged
      loop: "{{ interfaces }}"
      tags: enableintf

    - name: Configuring  trunks
      cisco.ios.ios_l2_interfaces:
        config:
          - name: "{{ item.name }}"
            mode: trunk
            trunk:
              allowed_vlans: 10-20,40
              native_vlan: "{{ item.native }}"
              # pruning_vlans: 10,20
              encapsulation: "{{ item.encap }}"
        state: merged
      loop: "{{ interfaces }}"
      when: "item.mode is defined and item.mode == 'trunk'"
      loop_control:
        label: "{{ item.name }}"
      tags: intftrunk

    - name: Configuring  access ports
      cisco.ios.ios_l2_interfaces:
        config:
          - name: "{{ item.name }}"
            mode: access
            access:
              vlan: "{{ item.access_vlan }}"
            voice:
              vlan: "{{ item.voice_vlan }}"
        state: merged
      loop: "{{ interfaces }}"
      loop_control:
        label: "{{ item.name }}"
      when: "item.mode is defined and item.mode == 'access'"
      tags: intfaccess



    - name: run 'show vlans' command
      ios_command:
        commands: show vlan brief
      register: myvlans

    - name: display value of "myvlans" variable
      ansible.builtin.debug:
        var: myvlans["stdout_lines"][0]

    - name: run 'show int trunk' trunk
      ios_command:
        commands: show interfaces trunk
      register: mytrunks

    - name: display value of "myvlans" variable
      ansible.builtin.debug:
        var: mytrunks["stdout_lines"][0]


...
