---
- name: Connecting to all specified devices and enable interfaces...
  hosts: all
  gather_facts: false

  tasks:
    - name: Configure ospf 1
      ios_ospfv2:
        config:
          processes:
          - process_id: "{{ ospf.process_id }}"
            router_id: "{{ ospf.router_id }}"
            #auto_cost:
             # reference_bandwidth: "{{ ospf.auto_cost.reference_bandwidth }}"
            network: 
              - address: "{{ item.address }}"
                area: "{{ item.area }}"
                wildcard_bits: "{{ item.wildcard_bits }}"
      when: ospf is defined
      loop: "{{ ospf_networks }}"
      tags: ospfproces

...
