---
- name: Connecting to all specified devices and enable interfaces...
  hosts: all
  gather_facts: false

  tasks:
    - name: Configuring Logging synchronous for console vty
      ios_config:
        lines:
          - logging synchronous
        parents: line vty 0 4
      tags: console

    - name: Turn on interfaces
      ios_interfaces:
        config:
          - name: "{{ item.name }}"
            description: "{{ item.description }}"
            enabled: false
        state: merged
      loop: "{{ interfaces }}"
      tags: enableintf

    - name: Configure switch interfaces as L3 interfaces
      ios_config:
        lines:
          - no switchport
        parents: interface {{ item.name }}
      loop: "{{ interfaces }}"
      loop_control:
        label: "{{ item.name }}"
      when: "item.L3 is defined"
      tags: L3intsw

    - name: Configure interface addresses
      ios_l3_interfaces:
        config:
          - name: "{{ item.name }}"
            ipv4:
              - address: "{{ item.ipv4 }}"
            ipv6:
              - address: "{{ item.ipv6 }}"
        state: merged
      loop: "{{ interfaces }}"
      loop_control:
        label: "{{ item.name }}"
      when: "item.mode is not defined"
      tags: addresses

    - name: Configure IPv6 link-local addresses
      cisco.ios.ios_config:
        lines:
          - ipv6 address {{ item.link_local | ansible.netcommon.ipaddr('address') }} link-local
        parents: interface {{ item.name }}
      loop: "{{ interfaces }}"
      loop_control:
        label: "{{ item.name }}"
      when: item.link_local is defined
      tags: linklocal

    - name: enable ip routing on switches
      ios_config:
        lines: "{{ item }}"
      loop:
        - ip routing
        - ipv6 unicast-routing
      tags: iprouting

    - name: run show ip int brief IPv4
      ios_command:
        commands: show ip interface brief
      register: myintipv4

    - name: display value of "myintipv4" variable
      debug:
        var: myintipv4["stdout_lines"][0]

    - name: run show ipv6 int brief IPv6
      ios_command:
        commands: show ipv6 interface brief
      register: myintipv6

    - name: display value of "myintipv6" variable
      debug:
        var: myintipv6["stdout_lines"][0]


...
