---
- name: Sample IOS show commands 
  hosts: routers
  gather_facts: no

  tasks:

  - name: GATHERING FACTS
    ios_facts:
      gather_subset: hardware

  - name: display current IOS version
    debug:
      var: network_resources.interfaces.description

  - name: run show ip int brie
    ios_command:
      commands: show ip interface brief
    register: myint

  - name: display value of "myint" variable
    debug:
      var: myint["stdout_lines"][0]

