interfaces:
 - name: GigabitEthernet0/0
   description: Link to R2 configured by Ansible
   ipv4: 172.16.0.2/30
   ipv6: "2001:db8:acad:a001::2/64"
   link_local: "fe80::1:2"
   area: "0"
 - name: GigabitEthernet0/1
   description: Link to D1 configured by Ansible
   ipv4: 10.10.0.1/30
   ipv6: "2001:db8:acad:1001::1/64"
   link_local: "fe80::1:1"
   area: "1"
ospf:
  process_id: 123
  router_id: 1.1.1.1
  auto_cost:
    reference_bandwidth: 1000
ospf_networks:
    - address: "172.16.0.0"
      wildcard_bits: "0.0.0.3"
      area: "0"
    - address: "10.10.0.0"
      wildcard_bits: "0.0.0.3"
      area: "1"