interfaces:
 - name: GigabitEthernet0/0
   description: Link to R1 configured by Ansible
   ipv4: 172.16.0.1/30
   ipv6: "2001:db8:acad:a001::1/64"
 - name: GigabitEthernet0/1
   description: Link to R3 configured by Ansible
   ipv4: 172.16.1.1/30
   ipv6: "2001:db8:acad:a002::1/64"
 - name: Loopback0
   description: Loopback 0 configured by Ansible
   ipv4: 209.165.200.224/27
   ipv6: "2001:db8:feed:209::1/64"
