interfaces:
 - name: GigabitEthernet0/0
   description: Link to R1 configured by Ansible
   ipv4: 172.16.0.1/30
   ipv6: "2001:db8:acad:a001::1/64"
   link_local: "fe80::2:1"
   area: "0"
 - name: GigabitEthernet0/1
   description: Link to R3 configured by Ansible
   ipv4: 172.16.1.1/30
   ipv6: "2001:db8:acad:a002::1/64"
   link_local: "fe80::2:2"
   area: "0"
 - name: Loopback 0
   description: Loopback 0 configured by Ansible
   ipv4: 209.165.200.225/27
   ipv6: "2001:db8:feed:209::1/64"
   link_local: fe80::2:3
   area: "0"
ospf:
  process_id: 123
  router_id: 2.2.2.1
  auto_cost:
    reference_bandwidth: 1000
ospf_networks:
  - address: "172.16.0.0"
    wildcard_bits: "0.0.0.3"
    area: "0"
  - address: "172.16.1.0"
    wildcard_bits: "0.0.0.3"
    area: "0"
